### ISSUE TITLE
OperationHeaders generation problem with headers containing a -

### ISSUE THREAD

**Issue by guillaumeserale** [christianhelle/refitter#26]
When generating Refit Interfaces for operations with header parameters, if the header key contains  a `-` , the resulting code contains an `AliasAs`, which is ignored by Refit when serializing the header parameters.
### Example
```yaml
parameters:
  - name: api-key
    in: header
    description: ''
    required: false
    schema:
      type: string
```

```csharp
   [Header("api_key"), AliasAs("api-key")] string api_key
```
